CREATE TABLE `repo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `owner` varchar(128) NOT NULL,
  `name` varchar(128) NOT NULL,
  `commit_count` int(11) NOT NULL DEFAULT 0,
  `min_date` datetime DEFAULT NULL,
  `max_date` datetime DEFAULT NULL,
  `repo_machine_name` varchar(64) DEFAULT NULL,
  `repo_dir` varchar(512) DEFAULT NULL,
  `numstat_machine_name` varchar(64) DEFAULT NULL,
  `numstat_dir` varchar(512) DEFAULT NULL,
  `last_cloned_date` datetime DEFAULT NULL,
  `last_numstat_date` datetime DEFAULT NULL,
  `last_analysis_date` datetime DEFAULT NULL,
  `delay_api_calls_until` datetime DEFAULT NULL,
  `retry_count` int(11) DEFAULT 0,
  `last_updated` datetime DEFAULT NULL,
  `failed_date` datetime DEFAULT NULL,
  `md5` char(32) DEFAULT md5(concat(`owner`,'	',`name`)),
  `last_machine` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `repoIdx` (`owner`,`name`),
  KEY `repo_last_updated_idx` (`last_updated`),
  KEY `composite_idx` (`id`,`repo_machine_name`,`numstat_machine_name`,`last_analysis_date`) USING BTREE,
  KEY `md5idx` (`md5`),
  KEY `alt_idx` (`owner`,`name`),
  KEY `macidx` (`last_machine`,`last_analysis_date`)
) ENGINE=InnoDB AUTO_INCREMENT=3412487 DEFAULT CHARSET=utf8mb4